package com.ai.mall.identity.application.service;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import com.ai.mall.identity.application.port.AuditRecorder;import com.ai.mall.identity.domain.model.rbac.Role;import com.ai.mall.identity.domain.repository.*;import java.util.*;import org.junit.jupiter.api.Test;
class RbacAdministrationApplicationServiceTest {
 @Test void invalidRoleSetIsRejectedBeforeAdminMutation(){var admins=mock(AdminUserRepository.class);var roles=mock(RoleRepository.class);var admin=com.ai.mall.identity.domain.model.admin.AdminUser.reconstitute(1,"admin","hash","ENABLED",1,1,List.of(),java.time.Instant.now(),java.time.Instant.now());when(admins.findById(1)).thenReturn(Optional.of(admin));when(roles.allEnabled(anyCollection())).thenReturn(false);var service=service(admins,roles,mock(PermissionRepository.class),mock(MenuRepository.class));assertThatThrownBy(()->service.replaceAdminRoles(9,1,List.of(2L,3L))).hasMessageContaining("role set");verify(admins,never()).replaceRoles(any());
 }
 @Test void builtInRoleCannotBeChangedOrDeleted(){var roles=mock(RoleRepository.class);when(roles.findById(1)).thenReturn(Optional.of(Role.reconstitute(1,"SUPER_ADMIN","Super",null,"ENABLED",true,List.of(4L),List.of(5L))));var service=service(mock(AdminUserRepository.class),roles,mock(PermissionRepository.class),mock(MenuRepository.class));assertThatThrownBy(()->service.updateRole(9,1,"x",null,"DISABLED")).hasMessageContaining("built-in");assertThatThrownBy(()->service.deleteRole(9,1)).hasMessageContaining("built-in");verify(roles,never()).save(any());verify(roles,never()).delete(any());}
 @Test void authorizationReplacementSavesAggregateAndInvalidatesMembers(){var roles=mock(RoleRepository.class);var permissions=mock(PermissionRepository.class);var menus=mock(MenuRepository.class);var role=Role.reconstitute(2,"OPS_ADMIN","Ops",null,"ENABLED",false,List.of(),List.of());when(roles.findById(2)).thenReturn(Optional.of(role));when(permissions.allEnabled(anyCollection())).thenReturn(true);when(menus.allEnabled(anyCollection())).thenReturn(true);service(mock(AdminUserRepository.class),roles,permissions,menus).replaceRoleAuthorizations(9,2,List.of(4L),List.of(5L));assertThat(role.permissionIds()).containsExactly(4L);assertThat(role.menuIds()).containsExactly(5L);verify(roles).saveAuthorizations(role);verify(roles).bumpMembersVersion(2);}
 private static RbacAdministrationApplicationService service(AdminUserRepository a,RoleRepository r,PermissionRepository p,MenuRepository m){return new RbacAdministrationApplicationService(a,r,p,m,mock(AuditRecorder.class));}
}
