package com.ai.mall.identity.domain.model.rbac;

public final class Menu {
    private final long id; private Long parentId; private String name; private MenuType type; private String path;
    private String componentKey; private String permissionCode; private int sortOrder; private boolean visible; private RbacStatus status;
    private Menu(long id,Long parentId,String name,String type,String path,String componentKey,String permissionCode,int sortOrder,boolean visible,String status){this.id=id; revise(parentId,name,type,path,componentKey,permissionCode,sortOrder,visible,status);}
    public static Menu create(Long parentId,String name,String type,String path,String componentKey,String permissionCode,int sortOrder,boolean visible){return new Menu(0,parentId,name,type,path,componentKey,permissionCode,sortOrder,visible,"ENABLED");}
    public static Menu reconstitute(long id,Long parentId,String name,String type,String path,String componentKey,String permissionCode,int sortOrder,boolean visible,String status){if(id<=0)throw new IllegalArgumentException("menu id must be positive");return new Menu(id,parentId,name,type,path,componentKey,permissionCode,sortOrder,visible,status);}
    public void revise(Long parentId,String name,String type,String path,String componentKey,String permissionCode,int sortOrder,boolean visible,String status){if(name==null||name.isBlank())throw new IllegalArgumentException("name is required");var parsed=MenuType.valueOf(type);if(parentId!=null&&parentId==id)throw new IllegalArgumentException("menu cannot be its own parent");if(parsed==MenuType.PAGE&&(path==null||!path.startsWith("/")||componentKey==null||componentKey.isBlank()))throw new IllegalArgumentException("PAGE requires internal path and componentKey");if(parsed==MenuType.ACTION&&(permissionCode==null||permissionCode.isBlank()))throw new IllegalArgumentException("ACTION requires permission code");this.parentId=parentId;this.name=name.trim();this.type=parsed;this.path=path;this.componentKey=componentKey;this.permissionCode=permissionCode;this.sortOrder=sortOrder;this.visible=visible;this.status=RbacStatus.valueOf(status);}
    public long id(){return id;}public Long parentId(){return parentId;}public String name(){return name;}public String type(){return type.name();}public String path(){return path;}public String componentKey(){return componentKey;}public String permissionCode(){return permissionCode;}public int sortOrder(){return sortOrder;}public boolean visible(){return visible;}public String status(){return status.name();}
    public enum MenuType { DIRECTORY, PAGE, ACTION }
}
